# CAMO Configuration

content_type:
  roadwork:
    model: 'ViT'
    detector_config: 'ViT_roadwork.yaml'  # Default model for 'general'
  face:
    model: 'UCF'
    detector_config: 'ucf_face.yaml'  # Default model for 'face'
    use_gate: True